ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "location" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "distance" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "price" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION NOT NULL DEFAULT 5.0;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "image" TEXT NOT NULL DEFAULT '';
